export const QUERY_KEYS = {
  TEST_KEY: 'TestKey',
  TEST_KEY2: 'TestKey2',
  GET_GAME_LIST: 'GET_GAME_LIST',
  LOGIN: 'LOGIN',
  GET_USER_INFO: 'GET_USER_INFO',
  DEACTIVATE: 'DEACTIVATE',
  GET_GAME_DETAIL: 'GET_GAME_DETAIL',
}

Object.freeze(QUERY_KEYS)
